Better typed Autocomplete
DoneDeal0/Talkr pull request #33
Opened 2023-02-22 13:43 UTC by dolie

Hello ! 
Thank you for this library. 🙏
I use it on my project. 👌🏻
Unfortunately, Sonarqube tells me this :
> `KeyPath<schema> | (string & {});`
> Remove this type without members or change this type intersection. Types without members, 'any' and 'never' should not be used in type intersections.  

So I modified the type to handle this.

2023-02-22 15:36 UTC, DoneDeal0 requested changes

2023-02-22 15:36 UTC, DoneDeal0 commented on src/models.ts
> +};
It would be easier to merge all dynamic suffixes into a single type. Also, Talkr may return more complex plural keys for certain languages. Here is an updated type:
```suggestion
type DynamicSuffix = Partial<{
  zero: string;
  one: string;
  two: string;
  few: string;
  many: string;
  female: string;
  male: string;
}>;
```

2023-02-22 15:36 UTC, DoneDeal0 commented on src/models.ts
> +  T extends plural | gender
Based on our updated `DynamicSuffix` type:
```suggestion
  T extends DynamicSuffix
```

2023-02-22 15:43 UTC, DoneDeal0 commented
Hi @dolie , 

Thanks for your pull request! Your idea is good, let's do it! However, I've added two change requests. If you agree with them, please update the pr and I'll merge it shortly afterwards.

2023-02-23 13:51 UTC, dolie commented
All done !
Tell me if it missing something 🙂

2023-02-23 14:02 UTC, merged

2023-02-23 15:01 UTC, DoneDeal0 commented
Thank you! I've released the code to npm. You are also cited in the [release note](https://github.com/DoneDeal0/Talkr/releases/tag/v3.4.0).